#!/usr/bin/env python3
"""The repository's import graph, read from the imports themselves.

ARCHITECTURE.md is written by hand where it says what a package is *for* -
no tool infers intent - and generated where it says what depends on what.
The generated half is the half that rots: a hand-drawn arrow survives the
refactor that deleted it, and a diagram nobody trusts is worse than none.

So this writes the diagram, the module table and the back-edge list into
ARCHITECTURE.md between markers, and `--check` fails when the file no
longer matches the code. Wire that into CI and the picture cannot drift
without someone being told.

Package level, not module level. There are 58 non-test modules here; a
graph of all of them is a hairball nobody reads, and the eight packages
are the layering someone actually has to hold in their head. Modules
appear in a table underneath with their fan-in, which is where "what
would I break if I changed this" is answered.

Usage:
    python scripts/module_map.py                 # print
    python scripts/module_map.py --write         # update ARCHITECTURE.md
    python scripts/module_map.py --check         # fail if it is stale
"""
from __future__ import annotations

import argparse
import ast
import collections
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
SKIP_DIRS = {".venv", "__pycache__", ".git", "wandb", "pictures", ".pytest_cache"}
START = "<!-- generated by scripts/module_map.py - do not edit below -->"
END = "<!-- end generated -->"


def python_files(root: Path):
    return sorted(p for p in root.rglob("*.py")
                  if not any(part in SKIP_DIRS for part in p.relative_to(root).parts))


def module_name(path: Path, root: Path) -> str:
    return ".".join(path.relative_to(root).with_suffix("").parts)


def scan(root: Path):
    """(modules, edges) for one tree, edges pointing at what is imported.

    Import statements only. A call through importlib or a name resolved at
    runtime is invisible here, which is the honest limit of reading source
    rather than running it - and the reason this graph is a map, not a
    proof.
    """
    files = python_files(root)
    packages = {p.relative_to(root).parts[0] for p in files if p.parent != root}
    modules = {module_name(p, root): p for p in files}
    edges = set()
    for name, path in modules.items():
        try:
            tree = ast.parse(path.read_text())
        except (SyntaxError, UnicodeDecodeError):
            continue
        for node in ast.walk(tree):
            targets = []
            if isinstance(node, ast.ImportFrom) and node.module:
                targets = [node.module]
            elif isinstance(node, ast.Import):
                targets = [alias.name for alias in node.names]
            for target in targets:
                if target.split(".")[0] in packages and target != name:
                    edges.add((name, target))
    return modules, sorted(edges), sorted(packages)


def package_of(name: str) -> str:
    return name.split(".")[0]


def package_edges(edges):
    counted = collections.Counter()
    for source, target in edges:
        if package_of(source) != package_of(target):
            counted[(package_of(source), package_of(target))] += 1
    return counted


def back_edges(edges):
    """Pairs of packages that import each other, and what makes the rarer
    direction exist.

    Named rather than counted, because a cycle held up by one import is a
    different problem from a cycle held up by twenty - the first is an
    afternoon's work and the second is the architecture.
    """
    counted = package_edges(edges)
    out = []
    for (a, b), forward in sorted(counted.items()):
        back = counted.get((b, a))
        if back is None or (forward, a) < (back, b):
            continue
        causes = sorted(f"{source} imports {target}" for source, target in edges
                        if package_of(source) == b and package_of(target) == a)
        out.append(((b, a), back, forward, causes))
    return out


def render(root: Path) -> str:
    modules, edges, packages = scan(root)
    counted = package_edges(edges)
    fan_in = collections.Counter()
    for _, target in edges:
        fan_in[target] += 1
    lines = [START, "", "```mermaid", "graph TD"]
    for package in packages:
        count = sum(1 for name in modules if package_of(name) == package)
        lines.append(f'  {package}["{package} ({count})"]')
    for (a, b), n in sorted(counted.items(), key=lambda kv: (-kv[1], kv[0])):
        lines.append(f"  {a} -->|{n}| {b}")
    lines += ["```", ""]

    # No file sizes here, tempting as they are: they change on every edit,
    # so the generated block would need regenerating after every commit and
    # the diff would say nothing.
    lines += ["| module | imported by |", "| --- | ---: |"]
    for name in sorted(modules):
        if package_of(name) == "tests" or name.endswith("__init__"):
            continue
        lines.append(f"| `{name}` | {fan_in.get(name, 0)} |")
    lines.append("")

    cycles = back_edges(edges)
    if cycles:
        lines.append("Packages that import each other:")
        lines.append("")
        for (a, b), few, many, causes in cycles:
            lines.append(f"- `{a}` -> `{b}` ({few}) against `{b}` -> `{a}` ({many}):")
            lines += [f"  - `{cause}`" for cause in causes]
        lines.append("")
    lines.append(END)
    return "\n".join(lines)


def splice(document: str, generated: str) -> str:
    if START in document and END in document:
        head = document.split(START)[0]
        tail = document.split(END, 1)[1]
        return head + generated + tail
    return document.rstrip() + "\n\n" + generated + "\n"


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", type=Path, default=REPO_ROOT)
    parser.add_argument("--doc", type=Path, default=REPO_ROOT / "ARCHITECTURE.md")
    parser.add_argument("--write", action="store_true", help="update the document")
    parser.add_argument("--check", action="store_true",
                        help="exit 1 if the document no longer matches the code")
    args = parser.parse_args()

    generated = render(args.root)
    if args.write:
        document = args.doc.read_text() if args.doc.exists() else ""
        args.doc.write_text(splice(document, generated))
        print(f"wrote {args.doc}")
    elif args.check:
        document = args.doc.read_text() if args.doc.exists() else ""
        if splice(document, generated) != document:
            raise SystemExit(f"{args.doc} is out of date - run "
                             f"python scripts/module_map.py --write")
        print(f"{args.doc} matches the code")
    else:
        print(generated)


if __name__ == "__main__":
    main()
